import os

base = "prior-authorization-ai"

directories = [
    f"{base}/backend/app/core",
    f"{base}/backend/app/db",
    f"{base}/backend/app/models",
    f"{base}/backend/app/repositories",
    f"{base}/backend/app/services",
    f"{base}/backend/app/rag",
    f"{base}/backend/app/api",
    f"{base}/backend/app/utils",
    f"{base}/backend/scripts",
    f"{base}/backend/data/raw/cms",
    f"{base}/backend/data/raw/synthea",
    f"{base}/backend/data/normalized/cms",
    f"{base}/backend/data/normalized/synthea",
    f"{base}/backend/data/uploads",
    f"{base}/backend/reports",
    f"{base}/backend/tests",
    f"{base}/frontend/src/api",
    f"{base}/frontend/src/components/glass",
    f"{base}/frontend/src/components/navigation",
    f"{base}/frontend/src/components/policy",
    f"{base}/frontend/src/components/evaluation",
    f"{base}/frontend/src/pages",
    f"{base}/frontend/src/hooks",
    f"{base}/frontend/src/types",
    f"{base}/frontend/src/utils",
    f"{base}/frontend/src/styles",
]

files = [
    f"{base}/README.md",
    f"{base}/.gitignore",
    f"{base}/.env.example",
    f"{base}/backend/.env",
    f"{base}/backend/requirements.txt",
    f"{base}/backend/app/__init__.py",
    f"{base}/backend/app/main.py",
    f"{base}/backend/app/core/__init__.py",
    f"{base}/backend/app/core/config.py",
    f"{base}/backend/app/core/logging.py",
    f"{base}/backend/app/core/constants.py",
    f"{base}/backend/app/db/__init__.py",
    f"{base}/backend/app/db/mongodb.py",
    f"{base}/backend/app/db/collections.py",
    f"{base}/backend/app/db/indexes.py",
    f"{base}/backend/app/models/__init__.py",
    f"{base}/backend/app/models/patient.py",
    f"{base}/backend/app/models/prior_auth.py",
    f"{base}/backend/app/models/cms_policy.py",
    f"{base}/backend/app/models/evidence.py",
    f"{base}/backend/app/models/evaluation.py",
    f"{base}/backend/app/repositories/__init__.py",
    f"{base}/backend/app/repositories/synthea_repository.py",
    f"{base}/backend/app/repositories/cms_repository.py",
    f"{base}/backend/app/repositories/case_repository.py",
    f"{base}/backend/app/services/__init__.py",
    f"{base}/backend/app/services/synthea_service.py",
    f"{base}/backend/app/services/pdf_extraction_service.py",
    f"{base}/backend/app/services/code_normalizer.py",
    f"{base}/backend/app/services/cms_relationship_service.py",
    f"{base}/backend/app/services/policy_resolution_service.py",
    f"{base}/backend/app/services/policy_rag_service.py",
    f"{base}/backend/app/services/criteria_service.py",
    f"{base}/backend/app/services/evidence_matching_service.py",
    f"{base}/backend/app/services/triage_service.py",
    f"{base}/backend/app/rag/__init__.py",
    f"{base}/backend/app/rag/chunker.py",
    f"{base}/backend/app/rag/embeddings.py",
    f"{base}/backend/app/rag/retriever.py",
    f"{base}/backend/app/rag/vector_index.py",
    f"{base}/backend/app/api/__init__.py",
    f"{base}/backend/app/api/health.py",
    f"{base}/backend/app/api/datasets.py",
    f"{base}/backend/app/api/patients.py",
    f"{base}/backend/app/api/upload.py",
    f"{base}/backend/app/api/policies.py",
    f"{base}/backend/app/api/evaluations.py",
    f"{base}/backend/app/utils/__init__.py",
    f"{base}/backend/app/utils/ids.py",
    f"{base}/backend/app/utils/dates.py",
    f"{base}/backend/app/utils/provenance.py",
    f"{base}/backend/scripts/audit_datasets.py",
    f"{base}/backend/scripts/import_cms.py",
    f"{base}/backend/scripts/import_synthea.py",
    f"{base}/backend/scripts/create_indexes.py",
    f"{base}/backend/scripts/validate_relationships.py",
    f"{base}/backend/scripts/build_rag_index.py",
]

for d in directories:
    os.makedirs(d, exist_ok=True)

for f in files:
    if not os.path.exists(f):
        open(f, 'w').close()
