# CMS Collections
CMS_ARTICLES = "cms_articles"
CMS_ICD_COVERED_ARTICLES = "cms_icd_covered_articles"
CMS_ICD_NONCOVERED_ARTICLES = "cms_icd_noncovered_articles"
CMS_ARTICLE_HCPCS = "cms_article_hcpcs"
CMS_RELATED_DOCUMENTS = "cms_related_documents"
CMS_LCD = "cms_lcd"
CMS_RELATED_NCD = "cms_related_ncd"
CMS_NCD = "cms_ncd"
CMS_CONTRACTORS = "cms_contractors"

# Synthea Collections
SYNTHEA_PATIENTS = "synthea_patients"
SYNTHEA_CONDITIONS = "synthea_conditions"
SYNTHEA_MEDICATIONS = "synthea_medications"
SYNTHEA_PROCEDURES = "synthea_procedures"
SYNTHEA_DIAGNOSTIC_RESULTS = "synthea_diagnostic_results"
SYNTHEA_VITAL_SIGNS = "synthea_vital_signs"
SYNTHEA_ENCOUNTERS = "synthea_encounters"
SYNTHEA_ALLERGIES = "synthea_allergies"
SYNTHEA_IMMUNIZATIONS = "synthea_immunizations"
SYNTHEA_CARE_PLANS = "synthea_care_plans"
SYNTHEA_SOCIAL_HISTORY = "synthea_social_history"
SYNTHEA_SURGERIES = "synthea_surgeries"
SYNTHEA_FUNCTIONAL_STATUS = "synthea_functional_status"
SYNTHEA_CLINICAL_ASSESSMENTS = "synthea_clinical_assessments"
SYNTHEA_FAMILY_HISTORY = "synthea_family_history"
SYNTHEA_REFERRALS = "synthea_referrals"
SYNTHEA_MEDICAL_EQUIPMENT = "synthea_medical_equipment"
SYNTHEA_CLAIMS = "synthea_claims"
SYNTHEA_COVERAGE = "synthea_coverage"
SYNTHEA_AUTHORIZATION_REQUESTS = "synthea_authorization_requests"
SYNTHEA_PROVIDERS = "synthea_providers"

# Aligned Cases Collections
ALIGNED_PRIOR_AUTH_CASES = "aligned_prior_auth_cases"
ALIGNED_CONDITION_ADDITIONS = "aligned_condition_additions"
